export const data = {
  result: {
    orders: [
      {
        date_change: "2024-10-02 18:11",
        date: "2024-10-02 16:55",
        date_arrival: "2024-10-02 17:35",
        date_departure: null,
        order_id: 4117474,
        user_id: 10573,
        order_type: 1,
        transaction: 671343813,
        payable_status: 1,
        ex_order_status: 0,
        service_id: 1,
        duration: 0,
        doer_city_id: 3,
        allowable_time: 0,
        cancellation_time: 1,
        reward: 25.5,
        booker_number: "M-0005043",
        arrival_number: "",
        departure_number: "",
        table: "",
        notes: "",
        location_address: "улица Мира, 23, Нск, Россия ",
        destination_address: "улица Титова, 32, Нск, Россия ",
        lang: "ru",
        allowable_subaddress: 3,
        coef_subaddress: 0.5,
        subaddress: [],
        send_params: {
          send_client_voucher: true,
          send_admin_voucher: false,
          send_client_doc: true,
          send_admin_doc: false,
        },
        passengers: [
          {
            name: "ТЕСТ",
            email: "testdevicesiway@gmail.com",
            phone: " 7 952 906-96-31",
            company: null,
            client_id: 591687,
            company_id: null,
          },
          {
            name: "ТЕСТ2222222222222",
            email: "testdevicesiway@gmail.com",
            phone: " 7 952 906-96-31",
            company: null,
            client_id: 591687,
            company_id: null,
          },
        ],
        passengers_number: 1,
        additional_address: false,
        cancellation_time_without_penalty: "2024-10-02T16:35:00+07:00",
        destination_address_object: {
          address: "улица Титова, 32, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Титова, 32, Новосибирск, Новосибирская обл., Россия, 630054",
            geometry: {
              location: {
                lat: 54.982165,
                lng: 82.868855,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.983513980291,
                  lng: 82.870203980292,
                },
                southwest: {
                  lat: 54.980816019708,
                  lng: 82.867506019709,
                },
              },
            },
            place_id: "ChIJ2SFHidHm30IR_cqVChDrAXM",
            plus_code: {
              compound_code:
                "XVJ9+VG Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XVJ9+VG",
            },
            types: [null],
          },
        },
        location_address_object: {
          address: "улица Мира, 23, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Мира, 23, Новосибирск, Новосибирская обл., Россия, 630024",
            geometry: {
              location: {
                lat: 54.9641619,
                lng: 82.9110016,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.965510880291,
                  lng: 82.912350580292,
                },
                southwest: {
                  lat: 54.962812919708,
                  lng: 82.909652619708,
                },
              },
            },
            place_id: "ChIJtQxiABDn30IR92PhirO_Y8w",
            plus_code: {
              compound_code:
                "XW76+MC Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XW76+MC",
            },
            types: [null],
          },
        },
        car_data: {
          car_class_id: 2,
          car_class: "Стандарт",
          models: "Hyundai Accent, Renault Talisman",
          capacity: 3,
          photo: "ozoyrm185w.png",
          deleted: false,
          description: null,
        },
        currency: "RUB",
        price: {
          price_id: 2959206,
          price: 644,
          price_subaddress: null,
        },
        additional_change_itinerary: 2,
        additional_wait: 2,
        fare_on_toll_road: 2,
        additional_payment_info: null,
        meeting_point: null,
        internal_number: "",
        viewers: ["79529069631"],
        coordinator: {
          phone: null,
          name: null,
        },
        additional_services: [],
        flexible_tariff: true,
        uuid: "d78279dd-80a3-11ef-ba90-bc2411598e4b",
        is_blocked_update: false,
        driver_data: {
          driver_name: "Даниил",
          driver_phone: "79529069631",
          driver_car: "Range Rover Range Rover B005TT54",
          driver_rating: "5",
          car_color: null,
        },
        is_fast_booking: false,
        pos: null,
        platform: 2,
        ffp_number: null,
        flexible_tariff_agreement: true,
        children_amount: 0,
        adults_amount: 1,
        service_provider: {
          id: 1,
          title: "Iway",
          deleted: false,
        },
        doer: null,
        cost_center: null,
        number: 3257,
        status: 2,
        start_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "A",
          train_carriage_number: null,
        },
        finish_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
        },
        customer: {
          name: "ТЕСТ2 ",
          email: "testdevicesiway@gmail.com",
          phone: "",
        },
        start_place_id: "ChIJtQxiABDn30IR92PhirO_Y8w",
        finish_place_id: "ChIJ2SFHidHm30IR_cqVChDrAXM",
      },
      {
        date_change: "2024-10-01 15:25",
        date: "2024-10-01 15:25",
        date_arrival: "2024-10-04 15:00",
        date_departure: null,
        order_id: 4117467,
        user_id: 10573,
        order_type: 12,
        transaction: 516836446,
        payable_status: 0,
        ex_order_status: 0,
        service_id: 1,
        duration: 0,
        doer_city_id: 3,
        allowable_time: 0,
        cancellation_time: 0,
        reward: 25.5,
        booker_number: "M-0005036",
        arrival_number: "",
        departure_number: "",
        table: "",
        notes: "",
        location_address: "улица Мира, 23, Нск, Россия",
        destination_address: "улица Титова, 32, Нск, Россия",
        lang: "ru",
        allowable_subaddress: 3,
        coef_subaddress: 0.5,
        subaddress: [],
        send_params: {
          send_client_voucher: true,
          send_admin_voucher: false,
          send_client_doc: true,
          send_admin_doc: false,
        },
        passengers: [
          {
            name: "ТЕСТ",
            email: "testdevicesiway@gmail.com",
            phone: "+7 952 906-96-31",
            company: null,
            client_id: 591687,
            company_id: null,
          },
        ],
        passengers_number: 1,
        additional_address: false,
        cancellation_time_without_penalty: "2024-10-04T15:00:00+07:00",
        destination_address_object: {
          address: "улица Титова, 32, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Титова, 32, Новосибирск, Новосибирская обл., Россия, 630054",
            geometry: {
              location: {
                lat: 54.982165,
                lng: 82.868855,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.983513980291,
                  lng: 82.870203980292,
                },
                southwest: {
                  lat: 54.980816019708,
                  lng: 82.867506019709,
                },
              },
            },
            place_id: "ChIJ2SFHidHm30IR_cqVChDrAXM",
            plus_code: {
              compound_code:
                "XVJ9+VG Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XVJ9+VG",
            },
            types: [null],
          },
        },
        location_address_object: {
          address: "улица Мира, 23, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Мира, 23, Новосибирск, Новосибирская обл., Россия, 630024",
            geometry: {
              location: {
                lat: 54.9641619,
                lng: 82.9110016,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.965510880291,
                  lng: 82.912350580292,
                },
                southwest: {
                  lat: 54.962812919708,
                  lng: 82.909652619708,
                },
              },
            },
            place_id: "ChIJtQxiABDn30IR92PhirO_Y8w",
            plus_code: {
              compound_code:
                "XW76+MC Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XW76+MC",
            },
            types: [null],
          },
        },
        car_data: {
          car_class_id: 2,
          car_class: "Стандарт",
          models: "Hyundai Accent, Renault Talisman",
          capacity: 3,
          photo: "ozoyrm185w.png",
          deleted: false,
          description: null,
        },
        currency: "RUB",
        price: {
          price_id: 2959206,
          price: 644,
          price_subaddress: null,
        },
        additional_change_itinerary: 2,
        additional_wait: 2,
        fare_on_toll_road: 2,
        additional_payment_info: null,
        meeting_point: null,
        internal_number: "",
        viewers: ["79529069631"],
        coordinator: {
          phone: null,
          name: null,
        },
        additional_services: [],
        flexible_tariff: true,
        uuid: null,
        is_blocked_update: false,
        driver_data: null,
        is_fast_booking: false,
        pos: null,
        platform: 2,
        ffp_number: null,
        flexible_tariff_agreement: true,
        children_amount: 0,
        adults_amount: 1,
        service_provider: {
          id: 1,
          title: "Iway",
          deleted: false,
        },
        doer: null,
        cost_center: null,
        number: null,
        status: 0,
        start_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
          train_carriage_number: null,
        },
        finish_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
        },
        customer: {
          name: "",
          email: "",
          phone: "",
        },
        start_place_id: null,
        finish_place_id: null,
      },
      {
        date_change: "2024-10-01 15:23",
        date: "2024-10-01 15:23",
        date_arrival: "2024-10-04 15:00",
        date_departure: null,
        order_id: 4117466,
        user_id: 10573,
        order_type: 12,
        transaction: 258445417,
        payable_status: 0,
        ex_order_status: 0,
        service_id: 1,
        duration: 0,
        doer_city_id: 3,
        allowable_time: 0,
        cancellation_time: 0,
        reward: 25.5,
        booker_number: "M-0005035",
        arrival_number: "",
        departure_number: "",
        table: "",
        notes: "",
        location_address: "улица Мира, 23, Нск, Россия",
        destination_address: "улица Титова, 32, Нск, Россия",
        lang: "ru",
        allowable_subaddress: 3,
        coef_subaddress: 0.5,
        subaddress: [],
        send_params: {
          send_client_voucher: true,
          send_admin_voucher: false,
          send_client_doc: true,
          send_admin_doc: false,
        },
        passengers: [
          {
            name: "ТЕСТ",
            email: "testdevicesiway@gmail.com",
            phone: "+7 952 906-96-31",
            company: null,
            client_id: 591687,
            company_id: null,
          },
        ],
        passengers_number: 1,
        additional_address: false,
        cancellation_time_without_penalty: "2024-10-04T15:00:00+07:00",
        destination_address_object: {
          address: "улица Титова, 32, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Титова, 32, Новосибирск, Новосибирская обл., Россия, 630054",
            geometry: {
              location: {
                lat: 54.982165,
                lng: 82.868855,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.983513980291,
                  lng: 82.870203980292,
                },
                southwest: {
                  lat: 54.980816019708,
                  lng: 82.867506019709,
                },
              },
            },
            place_id: "ChIJ2SFHidHm30IR_cqVChDrAXM",
            plus_code: {
              compound_code:
                "XVJ9+VG Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XVJ9+VG",
            },
            types: [null],
          },
        },
        location_address_object: {
          address: "улица Мира, 23, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Мира, 23, Новосибирск, Новосибирская обл., Россия, 630024",
            geometry: {
              location: {
                lat: 54.9641619,
                lng: 82.9110016,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.965510880291,
                  lng: 82.912350580292,
                },
                southwest: {
                  lat: 54.962812919708,
                  lng: 82.909652619708,
                },
              },
            },
            place_id: "ChIJtQxiABDn30IR92PhirO_Y8w",
            plus_code: {
              compound_code:
                "XW76+MC Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XW76+MC",
            },
            types: [null],
          },
        },
        car_data: {
          car_class_id: 2,
          car_class: "Стандарт",
          models: "Hyundai Accent, Renault Talisman",
          capacity: 3,
          photo: "ozoyrm185w.png",
          deleted: false,
          description: null,
        },
        currency: "RUB",
        price: {
          price_id: 2959206,
          price: 644,
          price_subaddress: null,
        },
        additional_change_itinerary: 2,
        additional_wait: 2,
        fare_on_toll_road: 2,
        additional_payment_info: null,
        meeting_point: null,
        internal_number: "",
        viewers: ["79529069631"],
        coordinator: {
          phone: null,
          name: null,
        },
        additional_services: [],
        flexible_tariff: true,
        uuid: null,
        is_blocked_update: false,
        driver_data: null,
        is_fast_booking: false,
        pos: null,
        platform: 2,
        ffp_number: null,
        flexible_tariff_agreement: true,
        children_amount: 0,
        adults_amount: 1,
        service_provider: {
          id: 1,
          title: "Iway",
          deleted: false,
        },
        doer: null,
        cost_center: null,
        number: null,
        status: 0,
        start_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
          train_carriage_number: null,
        },
        finish_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
        },
        customer: {
          name: "",
          email: "",
          phone: "",
        },
        start_place_id: null,
        finish_place_id: null,
      },
      {
        date_change: "2024-10-01 15:19",
        date: "2024-10-01 15:19",
        date_arrival: "2024-10-04 15:00",
        date_departure: null,
        order_id: 4117465,
        user_id: 10573,
        order_type: 12,
        transaction: 227161465,
        payable_status: 0,
        ex_order_status: 0,
        service_id: 1,
        duration: 0,
        doer_city_id: 3,
        allowable_time: 0,
        cancellation_time: 0,
        reward: 25.5,
        booker_number: "M-0005034",
        arrival_number: "",
        departure_number: "",
        table: "",
        notes: "",
        location_address: "улица Мира, 23, Нск, Россия",
        destination_address: "улица Титова, 32, Нск, Россия",
        lang: "ru",
        allowable_subaddress: 3,
        coef_subaddress: 0.5,
        subaddress: [],
        send_params: {
          send_client_voucher: true,
          send_admin_voucher: false,
          send_client_doc: true,
          send_admin_doc: false,
        },
        passengers: [
          {
            name: "ТЕСТ",
            email: "testdevicesiway@gmail.com",
            phone: "+7 952 906-96-31",
            company: null,
            client_id: 591687,
            company_id: null,
          },
        ],
        passengers_number: 1,
        additional_address: false,
        cancellation_time_without_penalty: "2024-10-04T15:00:00+07:00",
        destination_address_object: {
          address: "улица Титова, 32, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Титова, 32, Новосибирск, Новосибирская обл., Россия, 630054",
            geometry: {
              location: {
                lat: 54.982165,
                lng: 82.868855,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.983513980291,
                  lng: 82.870203980292,
                },
                southwest: {
                  lat: 54.980816019708,
                  lng: 82.867506019709,
                },
              },
            },
            place_id: "ChIJ2SFHidHm30IR_cqVChDrAXM",
            plus_code: {
              compound_code:
                "XVJ9+VG Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XVJ9+VG",
            },
            types: [null],
          },
        },
        location_address_object: {
          address: "улица Мира, 23, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Мира, 23, Новосибирск, Новосибирская обл., Россия, 630024",
            geometry: {
              location: {
                lat: 54.9641619,
                lng: 82.9110016,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.965510880291,
                  lng: 82.912350580292,
                },
                southwest: {
                  lat: 54.962812919708,
                  lng: 82.909652619708,
                },
              },
            },
            place_id: "ChIJtQxiABDn30IR92PhirO_Y8w",
            plus_code: {
              compound_code:
                "XW76+MC Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XW76+MC",
            },
            types: [null],
          },
        },
        car_data: {
          car_class_id: 2,
          car_class: "Стандарт",
          models: "Hyundai Accent, Renault Talisman",
          capacity: 3,
          photo: "ozoyrm185w.png",
          deleted: false,
          description: null,
        },
        currency: "RUB",
        price: {
          price_id: 2959206,
          price: 644,
          price_subaddress: null,
        },
        additional_change_itinerary: 2,
        additional_wait: 2,
        fare_on_toll_road: 2,
        additional_payment_info: null,
        meeting_point: null,
        internal_number: "",
        viewers: ["79529069631"],
        coordinator: {
          phone: null,
          name: null,
        },
        additional_services: [],
        flexible_tariff: true,
        uuid: null,
        is_blocked_update: false,
        driver_data: null,
        is_fast_booking: false,
        pos: null,
        platform: 2,
        ffp_number: null,
        flexible_tariff_agreement: true,
        children_amount: 0,
        adults_amount: 1,
        service_provider: {
          id: 1,
          title: "Iway",
          deleted: false,
        },
        doer: null,
        cost_center: null,
        number: null,
        status: 0,
        start_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
          train_carriage_number: null,
        },
        finish_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
        },
        customer: {
          name: "",
          email: "",
          phone: "",
        },
        start_place_id: null,
        finish_place_id: null,
      },
      {
        date_change: "2024-10-01 15:09",
        date: "2024-10-01 15:09",
        date_arrival: "2024-10-04 15:00",
        date_departure: null,
        order_id: 4117463,
        user_id: 10573,
        order_type: 12,
        transaction: 374738363,
        payable_status: 0,
        ex_order_status: 0,
        service_id: 1,
        duration: 0,
        doer_city_id: 3,
        allowable_time: 0,
        cancellation_time: 0,
        reward: 25.5,
        booker_number: "M-0005032",
        arrival_number: "",
        departure_number: "",
        table: "",
        notes: "",
        location_address: "улица Мира, 23, Нск, Россия",
        destination_address: "улица Титова, 32, Нск, Россия",
        lang: "ru",
        allowable_subaddress: 3,
        coef_subaddress: 0.5,
        subaddress: [],
        send_params: {
          send_client_voucher: true,
          send_admin_voucher: false,
          send_client_doc: true,
          send_admin_doc: false,
        },
        passengers: [
          {
            name: "ТЕСТ",
            email: "testdevicesiway@gmail.com",
            phone: "+7 952 906-96-31",
            company: null,
            client_id: 591687,
            company_id: null,
          },
        ],
        passengers_number: 1,
        additional_address: false,
        cancellation_time_without_penalty: "2024-10-04T15:00:00+07:00",
        destination_address_object: {
          address: "улица Титова, 32, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Титова, 32, Новосибирск, Новосибирская обл., Россия, 630054",
            geometry: {
              location: {
                lat: 54.982165,
                lng: 82.868855,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.983513980291,
                  lng: 82.870203980292,
                },
                southwest: {
                  lat: 54.980816019708,
                  lng: 82.867506019709,
                },
              },
            },
            place_id: "ChIJ2SFHidHm30IR_cqVChDrAXM",
            plus_code: {
              compound_code:
                "XVJ9+VG Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XVJ9+VG",
            },
            types: [null],
          },
        },
        location_address_object: {
          address: "улица Мира, 23, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Мира, 23, Новосибирск, Новосибирская обл., Россия, 630024",
            geometry: {
              location: {
                lat: 54.9641619,
                lng: 82.9110016,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.965510880291,
                  lng: 82.912350580292,
                },
                southwest: {
                  lat: 54.962812919708,
                  lng: 82.909652619708,
                },
              },
            },
            place_id: "ChIJtQxiABDn30IR92PhirO_Y8w",
            plus_code: {
              compound_code:
                "XW76+MC Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XW76+MC",
            },
            types: [null],
          },
        },
        car_data: {
          car_class_id: 2,
          car_class: "Стандарт",
          models: "Hyundai Accent, Renault Talisman",
          capacity: 3,
          photo: "ozoyrm185w.png",
          deleted: false,
          description: null,
        },
        currency: "RUB",
        price: {
          price_id: 2959206,
          price: 644,
          price_subaddress: null,
        },
        additional_change_itinerary: 2,
        additional_wait: 2,
        fare_on_toll_road: 2,
        additional_payment_info: null,
        meeting_point: null,
        internal_number: "",
        viewers: ["79529069631"],
        coordinator: {
          phone: null,
          name: null,
        },
        additional_services: [],
        flexible_tariff: true,
        uuid: null,
        is_blocked_update: false,
        driver_data: null,
        is_fast_booking: false,
        pos: null,
        platform: 2,
        ffp_number: null,
        flexible_tariff_agreement: true,
        children_amount: 0,
        adults_amount: 1,
        service_provider: {
          id: 1,
          title: "Iway",
          deleted: false,
        },
        doer: null,
        cost_center: null,
        number: null,
        status: 0,
        start_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
          train_carriage_number: null,
        },
        finish_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
        },
        customer: {
          name: "",
          email: "",
          phone: "",
        },
        start_place_id: null,
        finish_place_id: null,
      },
      {
        date_change: "2024-10-01 14:56",
        date: "2024-10-01 14:56",
        date_arrival: "2024-10-04 15:00",
        date_departure: null,
        order_id: 4117462,
        user_id: 10573,
        order_type: 12,
        transaction: 211121735,
        payable_status: 0,
        ex_order_status: 0,
        service_id: 1,
        duration: 0,
        doer_city_id: 3,
        allowable_time: 0,
        cancellation_time: 0,
        reward: 25.5,
        booker_number: "M-0005031",
        arrival_number: "",
        departure_number: "",
        table: "",
        notes: "",
        location_address: "улица Мира, 23, Нск, Россия",
        destination_address: "улица Титова, 32, Нск, Россия",
        lang: "ru",
        allowable_subaddress: 3,
        coef_subaddress: 0.5,
        subaddress: [],
        send_params: {
          send_client_voucher: true,
          send_admin_voucher: false,
          send_client_doc: true,
          send_admin_doc: false,
        },
        passengers: [
          {
            name: "ТЕСТ",
            email: "testdevicesiway@gmail.com",
            phone: "+7 952 906-96-31",
            company: null,
            client_id: 591687,
            company_id: null,
          },
        ],
        passengers_number: 1,
        additional_address: false,
        cancellation_time_without_penalty: "2024-10-04T15:00:00+07:00",
        destination_address_object: {
          address: "улица Титова, 32, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Титова, 32, Новосибирск, Новосибирская обл., Россия, 630054",
            geometry: {
              location: {
                lat: 54.982165,
                lng: 82.868855,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.983513980291,
                  lng: 82.870203980292,
                },
                southwest: {
                  lat: 54.980816019708,
                  lng: 82.867506019709,
                },
              },
            },
            place_id: "ChIJ2SFHidHm30IR_cqVChDrAXM",
            plus_code: {
              compound_code:
                "XVJ9+VG Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XVJ9+VG",
            },
            types: [null],
          },
        },
        location_address_object: {
          address: "улица Мира, 23, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Мира, 23, Новосибирск, Новосибирская обл., Россия, 630024",
            geometry: {
              location: {
                lat: 54.9641619,
                lng: 82.9110016,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.965510880291,
                  lng: 82.912350580292,
                },
                southwest: {
                  lat: 54.962812919708,
                  lng: 82.909652619708,
                },
              },
            },
            place_id: "ChIJtQxiABDn30IR92PhirO_Y8w",
            plus_code: {
              compound_code:
                "XW76+MC Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XW76+MC",
            },
            types: [null],
          },
        },
        car_data: {
          car_class_id: 2,
          car_class: "Стандарт",
          models: "Hyundai Accent, Renault Talisman",
          capacity: 3,
          photo: "ozoyrm185w.png",
          deleted: false,
          description: null,
        },
        currency: "RUB",
        price: {
          price_id: 2959206,
          price: 644,
          price_subaddress: null,
        },
        additional_change_itinerary: 2,
        additional_wait: 2,
        fare_on_toll_road: 2,
        additional_payment_info: null,
        meeting_point: null,
        internal_number: "",
        viewers: ["79529069631"],
        coordinator: {
          phone: null,
          name: null,
        },
        additional_services: [],
        flexible_tariff: true,
        uuid: null,
        is_blocked_update: false,
        driver_data: null,
        is_fast_booking: false,
        pos: null,
        platform: 2,
        ffp_number: null,
        flexible_tariff_agreement: true,
        children_amount: 0,
        adults_amount: 1,
        service_provider: {
          id: 1,
          title: "Iway",
          deleted: false,
        },
        doer: null,
        cost_center: null,
        number: null,
        status: 0,
        start_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
          train_carriage_number: null,
        },
        finish_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
        },
        customer: {
          name: "",
          email: "",
          phone: "",
        },
        start_place_id: null,
        finish_place_id: null,
      },
      {
        date_change: "2024-10-01 14:43",
        date: "2024-10-01 14:43",
        date_arrival: "2024-10-04 20:55",
        date_departure: null,
        order_id: 4117461,
        user_id: 10573,
        order_type: 12,
        transaction: 142138531,
        payable_status: 0,
        ex_order_status: 0,
        service_id: 1,
        duration: 0,
        doer_city_id: 3,
        allowable_time: 0,
        cancellation_time: 0,
        reward: 25.5,
        booker_number: "M-0005030",
        arrival_number: "",
        departure_number: "",
        table: "",
        notes: "",
        location_address: "улица Мира, 23, Нск, Россия",
        destination_address: "улица Титова, 32, Нск, Россия",
        lang: "ru",
        allowable_subaddress: 3,
        coef_subaddress: 0.5,
        subaddress: [],
        send_params: {
          send_client_voucher: true,
          send_admin_voucher: false,
          send_client_doc: true,
          send_admin_doc: false,
        },
        passengers: [
          {
            name: "ТЕСТ",
            email: "testdevicesiway@gmail.com",
            phone: "+7 952 906-96-31",
            company: null,
            client_id: 591687,
            company_id: null,
          },
        ],
        passengers_number: 1,
        additional_address: false,
        cancellation_time_without_penalty: "2024-10-04T20:55:00+07:00",
        destination_address_object: {
          address: "улица Титова, 32, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Титова, 32, Новосибирск, Новосибирская обл., Россия, 630054",
            geometry: {
              location: {
                lat: 54.982165,
                lng: 82.868855,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.983513980291,
                  lng: 82.870203980292,
                },
                southwest: {
                  lat: 54.980816019708,
                  lng: 82.867506019709,
                },
              },
            },
            place_id: "ChIJ2SFHidHm30IR_cqVChDrAXM",
            plus_code: {
              compound_code:
                "XVJ9+VG Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XVJ9+VG",
            },
            types: [null],
          },
        },
        location_address_object: {
          address: "улица Мира, 23, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Мира, 23, Новосибирск, Новосибирская обл., Россия, 630024",
            geometry: {
              location: {
                lat: 54.9641619,
                lng: 82.9110016,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.965510880291,
                  lng: 82.912350580292,
                },
                southwest: {
                  lat: 54.962812919708,
                  lng: 82.909652619708,
                },
              },
            },
            place_id: "ChIJtQxiABDn30IR92PhirO_Y8w",
            plus_code: {
              compound_code:
                "XW76+MC Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XW76+MC",
            },
            types: [null],
          },
        },
        car_data: {
          car_class_id: 2,
          car_class: "Стандарт",
          models: "Hyundai Accent, Renault Talisman",
          capacity: 3,
          photo: "ozoyrm185w.png",
          deleted: false,
          description: null,
        },
        currency: "RUB",
        price: {
          price_id: 2959206,
          price: 644,
          price_subaddress: null,
        },
        additional_change_itinerary: 2,
        additional_wait: 2,
        fare_on_toll_road: 2,
        additional_payment_info: null,
        meeting_point: null,
        internal_number: "",
        viewers: ["79529069631"],
        coordinator: {
          phone: null,
          name: null,
        },
        additional_services: [],
        flexible_tariff: true,
        uuid: null,
        is_blocked_update: false,
        driver_data: null,
        is_fast_booking: false,
        pos: null,
        platform: 2,
        ffp_number: null,
        flexible_tariff_agreement: true,
        children_amount: 0,
        adults_amount: 1,
        service_provider: {
          id: 1,
          title: "Iway",
          deleted: false,
        },
        doer: null,
        cost_center: null,
        number: null,
        status: 0,
        start_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
          train_carriage_number: null,
        },
        finish_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
        },
        customer: {
          name: "",
          email: "",
          phone: "",
        },
        start_place_id: null,
        finish_place_id: null,
      },
      {
        date_change: "2024-10-01 14:31",
        date: "2024-10-01 14:31",
        date_arrival: "2024-10-04 13:25",
        date_departure: null,
        order_id: 4117456,
        user_id: 10573,
        order_type: 12,
        transaction: 286511112,
        payable_status: 0,
        ex_order_status: 0,
        service_id: 1,
        duration: 0,
        doer_city_id: 3,
        allowable_time: 0,
        cancellation_time: 0,
        reward: 25.5,
        booker_number: "M-0005025",
        arrival_number: "",
        departure_number: "",
        table: "",
        notes: "",
        location_address: "улица Мира, 23, Нск, Россия",
        destination_address: "улица Титова, 32, Нск, Россия",
        lang: "ru",
        allowable_subaddress: 3,
        coef_subaddress: 0.5,
        subaddress: [],
        send_params: {
          send_client_voucher: true,
          send_admin_voucher: false,
          send_client_doc: true,
          send_admin_doc: false,
        },
        passengers: [
          {
            name: "ТЕСТ",
            email: "testdevicesiway@gmail.com",
            phone: "+7 952 906-96-31",
            company: null,
            client_id: 591687,
            company_id: null,
          },
        ],
        passengers_number: 1,
        additional_address: false,
        cancellation_time_without_penalty: "2024-10-04T13:25:00+07:00",
        destination_address_object: {
          address: "улица Титова, 32, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Титова, 32, Новосибирск, Новосибирская обл., Россия, 630054",
            geometry: {
              location: {
                lat: 54.982165,
                lng: 82.868855,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.983513980291,
                  lng: 82.870203980292,
                },
                southwest: {
                  lat: 54.980816019708,
                  lng: 82.867506019709,
                },
              },
            },
            place_id: "ChIJ2SFHidHm30IR_cqVChDrAXM",
            plus_code: {
              compound_code:
                "XVJ9+VG Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XVJ9+VG",
            },
            types: [null],
          },
        },
        location_address_object: {
          address: "улица Мира, 23, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Мира, 23, Новосибирск, Новосибирская обл., Россия, 630024",
            geometry: {
              location: {
                lat: 54.9641619,
                lng: 82.9110016,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.965510880291,
                  lng: 82.912350580292,
                },
                southwest: {
                  lat: 54.962812919708,
                  lng: 82.909652619708,
                },
              },
            },
            place_id: "ChIJtQxiABDn30IR92PhirO_Y8w",
            plus_code: {
              compound_code:
                "XW76+MC Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XW76+MC",
            },
            types: [null],
          },
        },
        car_data: {
          car_class_id: 2,
          car_class: "Стандарт",
          models: "Hyundai Accent, Renault Talisman",
          capacity: 3,
          photo: "ozoyrm185w.png",
          deleted: false,
          description: null,
        },
        currency: "RUB",
        price: {
          price_id: 2959206,
          price: 644,
          price_subaddress: null,
        },
        additional_change_itinerary: 2,
        additional_wait: 2,
        fare_on_toll_road: 2,
        additional_payment_info: null,
        meeting_point: null,
        internal_number: "",
        viewers: ["79529069631"],
        coordinator: {
          phone: null,
          name: null,
        },
        additional_services: [],
        flexible_tariff: true,
        uuid: null,
        is_blocked_update: false,
        driver_data: null,
        is_fast_booking: false,
        pos: null,
        platform: 2,
        ffp_number: null,
        flexible_tariff_agreement: true,
        children_amount: 0,
        adults_amount: 1,
        service_provider: {
          id: 1,
          title: "Iway",
          deleted: false,
        },
        doer: null,
        cost_center: null,
        number: null,
        status: 0,
        start_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
          train_carriage_number: null,
        },
        finish_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
        },
        customer: {
          name: "",
          email: "",
          phone: "",
        },
        start_place_id: null,
        finish_place_id: null,
      },
      {
        date_change: "2024-10-01 14:28",
        date: "2024-10-01 14:28",
        date_arrival: "2024-10-04 13:25",
        date_departure: null,
        order_id: 4117453,
        user_id: 10573,
        order_type: 12,
        transaction: 561136184,
        payable_status: 0,
        ex_order_status: 0,
        service_id: 1,
        duration: 0,
        doer_city_id: 3,
        allowable_time: 0,
        cancellation_time: 0,
        reward: 25.5,
        booker_number: "M-0005022",
        arrival_number: "",
        departure_number: "",
        table: "",
        notes: "",
        location_address: "улица Мира, 23, Нск, Россия",
        destination_address: "улица Титова, 32, Нск, Россия",
        lang: "ru",
        allowable_subaddress: 3,
        coef_subaddress: 0.5,
        subaddress: [],
        send_params: {
          send_client_voucher: true,
          send_admin_voucher: false,
          send_client_doc: true,
          send_admin_doc: false,
        },
        passengers: [
          {
            name: "ТЕСТ",
            email: "testdevicesiway@gmail.com",
            phone: "+7 952 906-96-31",
            company: null,
            client_id: 591687,
            company_id: null,
          },
        ],
        passengers_number: 1,
        additional_address: false,
        cancellation_time_without_penalty: "2024-10-04T13:25:00+07:00",
        destination_address_object: {
          address: "улица Титова, 32, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Титова, 32, Новосибирск, Новосибирская обл., Россия, 630054",
            geometry: {
              location: {
                lat: 54.982165,
                lng: 82.868855,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.983513980291,
                  lng: 82.870203980292,
                },
                southwest: {
                  lat: 54.980816019708,
                  lng: 82.867506019709,
                },
              },
            },
            place_id: "ChIJ2SFHidHm30IR_cqVChDrAXM",
            plus_code: {
              compound_code:
                "XVJ9+VG Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XVJ9+VG",
            },
            types: [null],
          },
        },
        location_address_object: {
          address: "улица Мира, 23, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Мира, 23, Новосибирск, Новосибирская обл., Россия, 630024",
            geometry: {
              location: {
                lat: 54.9641619,
                lng: 82.9110016,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.965510880291,
                  lng: 82.912350580292,
                },
                southwest: {
                  lat: 54.962812919708,
                  lng: 82.909652619708,
                },
              },
            },
            place_id: "ChIJtQxiABDn30IR92PhirO_Y8w",
            plus_code: {
              compound_code:
                "XW76+MC Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XW76+MC",
            },
            types: [null],
          },
        },
        car_data: {
          car_class_id: 2,
          car_class: "Стандарт",
          models: "Hyundai Accent, Renault Talisman",
          capacity: 3,
          photo: "ozoyrm185w.png",
          deleted: false,
          description: null,
        },
        currency: "RUB",
        price: {
          price_id: 2959206,
          price: 644,
          price_subaddress: null,
        },
        additional_change_itinerary: 2,
        additional_wait: 2,
        fare_on_toll_road: 2,
        additional_payment_info: null,
        meeting_point: null,
        internal_number: "",
        viewers: ["79529069631"],
        coordinator: {
          phone: null,
          name: null,
        },
        additional_services: [],
        flexible_tariff: true,
        uuid: null,
        is_blocked_update: false,
        driver_data: null,
        is_fast_booking: false,
        pos: null,
        platform: 2,
        ffp_number: null,
        flexible_tariff_agreement: true,
        children_amount: 0,
        adults_amount: 1,
        service_provider: {
          id: 1,
          title: "Iway",
          deleted: false,
        },
        doer: null,
        cost_center: null,
        number: null,
        status: 0,
        start_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
          train_carriage_number: null,
        },
        finish_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
        },
        customer: {
          name: "",
          email: "",
          phone: "",
        },
        start_place_id: null,
        finish_place_id: null,
      },
      {
        date_change: "2024-10-01 14:21",
        date: "2024-10-01 14:21",
        date_arrival: "2024-10-04 13:25",
        date_departure: null,
        order_id: 4117448,
        user_id: 10573,
        order_type: 12,
        transaction: 111717137,
        payable_status: 0,
        ex_order_status: 0,
        service_id: 1,
        duration: 0,
        doer_city_id: 3,
        allowable_time: 0,
        cancellation_time: 0,
        reward: 25.5,
        booker_number: "M-0005017",
        arrival_number: "",
        departure_number: "",
        table: "",
        notes: "",
        location_address: "улица Мира, 23, Нск, Россия",
        destination_address: "улица Титова, 32, Нск, Россия",
        lang: "ru",
        allowable_subaddress: 3,
        coef_subaddress: 0.5,
        subaddress: [],
        send_params: {
          send_client_voucher: true,
          send_admin_voucher: false,
          send_client_doc: true,
          send_admin_doc: false,
        },
        passengers: [
          {
            name: "ТЕСТ",
            email: "testdevicesiway@gmail.com",
            phone: "+7 952 906-96-31",
            company: null,
            client_id: 591687,
            company_id: null,
          },
        ],
        passengers_number: 1,
        additional_address: false,
        cancellation_time_without_penalty: "2024-10-04T13:25:00+07:00",
        destination_address_object: {
          address: "улица Титова, 32, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Титова, 32, Новосибирск, Новосибирская обл., Россия, 630054",
            geometry: {
              location: {
                lat: 54.982165,
                lng: 82.868855,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.983513980291,
                  lng: 82.870203980292,
                },
                southwest: {
                  lat: 54.980816019708,
                  lng: 82.867506019709,
                },
              },
            },
            place_id: "ChIJ2SFHidHm30IR_cqVChDrAXM",
            plus_code: {
              compound_code:
                "XVJ9+VG Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XVJ9+VG",
            },
            types: [null],
          },
        },
        location_address_object: {
          address: "улица Мира, 23, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Мира, 23, Новосибирск, Новосибирская обл., Россия, 630024",
            geometry: {
              location: {
                lat: 54.9641619,
                lng: 82.9110016,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.965510880291,
                  lng: 82.912350580292,
                },
                southwest: {
                  lat: 54.962812919708,
                  lng: 82.909652619708,
                },
              },
            },
            place_id: "ChIJtQxiABDn30IR92PhirO_Y8w",
            plus_code: {
              compound_code:
                "XW76+MC Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XW76+MC",
            },
            types: [null],
          },
        },
        car_data: {
          car_class_id: 2,
          car_class: "Стандарт",
          models: "Hyundai Accent, Renault Talisman",
          capacity: 3,
          photo: "ozoyrm185w.png",
          deleted: false,
          description: null,
        },
        currency: "RUB",
        price: {
          price_id: 2959206,
          price: 644,
          price_subaddress: null,
        },
        additional_change_itinerary: 2,
        additional_wait: 2,
        fare_on_toll_road: 2,
        additional_payment_info: null,
        meeting_point: null,
        internal_number: "",
        viewers: ["79529069631"],
        coordinator: {
          phone: null,
          name: null,
        },
        additional_services: [],
        flexible_tariff: true,
        uuid: null,
        is_blocked_update: false,
        driver_data: null,
        is_fast_booking: false,
        pos: null,
        platform: 2,
        ffp_number: null,
        flexible_tariff_agreement: true,
        children_amount: 0,
        adults_amount: 1,
        service_provider: {
          id: 1,
          title: "Iway",
          deleted: false,
        },
        doer: null,
        cost_center: null,
        number: null,
        status: 0,
        start_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
          train_carriage_number: null,
        },
        finish_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
        },
        customer: {
          name: "",
          email: "",
          phone: "",
        },
        start_place_id: null,
        finish_place_id: null,
      },
      {
        date_change: "2024-10-01 13:14",
        date: "2024-10-01 13:14",
        date_arrival: "2024-10-04 13:25",
        date_departure: null,
        order_id: 4117435,
        user_id: 10573,
        order_type: 12,
        transaction: 823476726,
        payable_status: 0,
        ex_order_status: 0,
        service_id: 1,
        duration: 0,
        doer_city_id: 3,
        allowable_time: 0,
        cancellation_time: 0,
        reward: 25.5,
        booker_number: "M-0005004",
        arrival_number: "",
        departure_number: "",
        table: "",
        notes: "",
        location_address: "улица Мира, 23, Нск, Россия",
        destination_address: "улица Титова, 32, Нск, Россия",
        lang: "ru",
        allowable_subaddress: 3,
        coef_subaddress: 0.5,
        subaddress: [],
        send_params: {
          send_client_voucher: true,
          send_admin_voucher: false,
          send_client_doc: true,
          send_admin_doc: false,
        },
        passengers: [
          {
            name: "ТЕСТ",
            email: "testdevicesiway@gmail.com",
            phone: "+7 952 906-96-31",
            company: null,
            client_id: 591687,
            company_id: null,
          },
          {
            name: "ТЕСТ!!!!!!!",
            email: "testdevicesiway@gmail.com",
            phone: "+7 952 906-96-31",
            company: null,
            client_id: 591685,
            company_id: null,
          },
        ],
        passengers_number: 1,
        additional_address: false,
        cancellation_time_without_penalty: "2024-10-04T13:25:00+07:00",
        destination_address_object: {
          address: "улица Титова, 32, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Титова, 32, Новосибирск, Новосибирская обл., Россия, 630054",
            geometry: {
              location: {
                lat: 54.982165,
                lng: 82.868855,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.983513980291,
                  lng: 82.870203980292,
                },
                southwest: {
                  lat: 54.980816019708,
                  lng: 82.867506019709,
                },
              },
            },
            place_id: "ChIJ2SFHidHm30IR_cqVChDrAXM",
            plus_code: {
              compound_code:
                "XVJ9+VG Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XVJ9+VG",
            },
            types: [null],
          },
        },
        location_address_object: {
          address: "улица Мира, 23, Нск, Россия",
          geo_check: true,
          geo_data: {
            address_components: [null, null, null, null, null, null, null],
            formatted_address:
              "ул. Мира, 23, Новосибирск, Новосибирская обл., Россия, 630024",
            geometry: {
              location: {
                lat: 54.9641619,
                lng: 82.9110016,
              },
              location_type: "ROOFTOP",
              viewport: {
                northeast: {
                  lat: 54.965510880291,
                  lng: 82.912350580292,
                },
                southwest: {
                  lat: 54.962812919708,
                  lng: 82.909652619708,
                },
              },
            },
            place_id: "ChIJtQxiABDn30IR92PhirO_Y8w",
            plus_code: {
              compound_code:
                "XW76+MC Новосибирск, Новосибирская область, Россия",
              global_code: "9M64XW76+MC",
            },
            types: [null],
          },
        },
        car_data: {
          car_class_id: 2,
          car_class: "Стандарт",
          models: "Hyundai Accent, Renault Talisman",
          capacity: 3,
          photo: "ozoyrm185w.png",
          deleted: false,
          description: null,
        },
        currency: "RUB",
        price: {
          price_id: 2959206,
          price: 644,
          price_subaddress: null,
        },
        additional_change_itinerary: 2,
        additional_wait: 2,
        fare_on_toll_road: 2,
        additional_payment_info: null,
        meeting_point: null,
        internal_number: "",
        viewers: ["79529069631"],
        coordinator: {
          phone: null,
          name: null,
        },
        additional_services: [],
        flexible_tariff: true,
        uuid: null,
        is_blocked_update: false,
        driver_data: null,
        is_fast_booking: false,
        pos: null,
        platform: 2,
        ffp_number: null,
        flexible_tariff_agreement: true,
        children_amount: 0,
        adults_amount: 1,
        service_provider: {
          id: 1,
          title: "Iway",
          deleted: false,
        },
        doer: null,
        cost_center: null,
        number: null,
        status: 0,
        start_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
          train_carriage_number: null,
        },
        finish_place: {
          place_id: 9,
          title: "Новосибирск",
          type: 1,
          type_title: "в черте города",
          city_id: 4549,
          city: "Новосибирск",
          terminal_number: "",
        },
        customer: {
          name: "",
          email: "",
          phone: "",
        },
        start_place_id: null,
        finish_place_id: null,
      },
    ],
    page_data: {
      page: 1,
      items_on_page: 11,
      total_items: 3542,
      page_count: 322,
    },
  },
  error: null,
  "x-uuid": "42b57ee6-6f19-3fbc-88c6-6b6e45b8d64f",
};
